sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.stats:
            contexts: [admin]
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    dashboard:
        blocks:
            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code:  admin.link
                    icon:  fa-magic
                    text:  Links
                    color: bg-aqua

            -
                class:    col-lg-3 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code:  admin.site
                    icon:  fa-magic
                    text:  Sites
                    color: bg-aqua

services:
    admin.site:
        class: App\Admin\SiteAdmin
        arguments: [~, App\Entity\Site, ~, "@doctrine.orm.entity_manager"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Site }
        public: true

    admin.link:
        class: App\Admin\LinkAdmin
        arguments: [~, App\Entity\Link, ~, "@doctrine.orm.entity_manager"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Link }
        public: true
