version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app

  app:
    image: jeboehm/uh.cx:latest-dev
    restart: always

  coverage:
    image: jeboehm/uh.cx:latest-dev
    volumes:
      - ./build:/var/www/html/build:rw

  coveralls:
    image: jeboehm/uh.cx:latest-dev
    volumes:
      - ./build:/var/www/html/build:rw
      - ./.git:/var/www/html/.git:rw
