imports:
    - { resource: services.yml }

parameters:
    env(GA_TRACKING): ""
    env(COOKIE_WARNING): false

framework:
    secret:          "%env(APP_SECRET)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  en
    trusted_hosts:   ~
    session:
        handler_id:  null
        name: uhcx
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ga_tracking:  "%env(GA_TRACKING)%"
        cookie_warning:  "%env(COOKIE_WARNING)%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:         pdo_mysql
        host:           "%env(MYSQL_HOST)%"
        dbname:         "%env(MYSQL_DB)%"
        user:           "%env(MYSQL_USER)%"
        password:       "%env(MYSQL_PASSWORD)%"
        charset:        UTF8
        server_version: 5.7

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            context:
                class: AppBundle\Doctrine\Filter\ContextFilter

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            softdeleteable: true
