services:
    app.command.site_create:
        class: AppBundle\Command\SiteCreateCommand
        arguments: ['site:create','@doctrine.orm.entity_manager', '@validator']
        tags:
            - { name: console.command }

    app.command.site_list:
        class: AppBundle\Command\SiteListCommand
        arguments: ['site:list', '@app.repository.site']
        tags:
            - { name: console.command }

    app.form.type.link:
        class: AppBundle\Form\Type\LinkType
        tags:
            - { name: form.type }

    app.service.context:
        class: AppBundle\Service\ContextService
        arguments: ['@request_stack', '@app.repository.site']

    app.service.feed:
        class: AppBundle\Service\FeedService
        arguments: ['@app.repository.link', '@app.service.context']

    app.service.url:
        class: AppBundle\Service\UrlService
        arguments: ['@app.service.context']

    app.repository.site:
        class: AppBundle\Repository\SiteRepository
        public: false
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['AppBundle\Entity\Site']

    app.repository.link:
        class: AppBundle\Repository\LinkRepository
        public: false
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['AppBundle\Entity\Link']

    app.subscriber.doctrine.context_filter:
        class: AppBundle\Subscriber\Doctrine\ContextFilterSubscriber
        arguments: ['@doctrine.orm.entity_manager', '@app.service.context']
        tags:
            - { name: kernel.event_subscriber }

    app.subscriber.preview_page_redirect:
        class: AppBundle\Subscriber\PreviewPageRedirectSubscriber
        arguments: ['@app.service.context']
        tags:
            - { name: kernel.event_subscriber }

    app.twig.context_extension:
        class: AppBundle\Twig\ContextExtension
        arguments: ['@app.service.context']
        tags:
            - { name: twig.extension }

    app.twig.link_extension:
        class: AppBundle\Twig\LinkExtension
        arguments: ['@app.service.url']
        tags:
            - { name: twig.extension }

    app.manager.link:
        class: AppBundle\Manager\LinkManager
        arguments: ['@doctrine.orm.entity_manager', '@app.service.context']

    app.manager.hit:
        class: AppBundle\Manager\HitManager
        arguments: ['@doctrine.orm.entity_manager', '@app.service.context']

    app.validator.constraint.url_blacklist:
        class: AppBundle\Validator\Constraint\UrlBlacklistValidator
        arguments: ['@app.repository.site']
        tags:
            - { name: validator.constraint_validator, alias: url_blacklist }
